# vim: et ts=2 sw=2
language: python
python:
  - "3.4"
  - "3.5-dev"
  - "3.6-dev"
  - "3.7-dev"
addons:
  hosts:
  - hostname.domain.com
install:
  - sudo apt-get install -y apache2 openssl
  - |
    if [ $TRAVIS_PYTHON_VERSION == "3.4" ]; then
      sudo apt-get install -y libapache2-mod-wsgi-py3;
    else
      sudo apt-get install -y apache2-dev
      pip install --upgrade mod_wsgi;
    fi
  - pip install --upgrade flask pylint pyvmomi PyYAML requests argparse
before_script:
  - sudo mkdir /etc/apache2/ssl
  - sudo openssl req -nodes -new -x509 -newkey rsa:2048
    -keyout /etc/apache2/ssl/hostname.domain.com.key
    -out /etc/apache2/ssl/hostname.domain.com.cert
    -days 1 -subj "/CN=hostname.domain.com"
  - sed -i "s,Directory /path/to/vctools,Directory $TRAVIS_BUILD_DIR," examples/api/api.conf
  - sed -i "s,/path/to/vctools,$TRAVIS_BUILD_DIR," examples/api/api.conf
  - sed -i "s,/path/to/vctools,$TRAVIS_BUILD_DIR," examples/api/api.wsgi
  - |
    if [ $TRAVIS_PYTHON_VERSION != "3.4" ]; then
      mod_wsgi-express module-config >> examples/api/api.conf
      sed -i "/WSGIDaemonProcess/ s,$, python-home=$VIRTUAL_ENV," examples/api/api.conf
    fi
  - sudo sed -i "s,www-data,travis,g" /etc/apache2/envvars
  - sudo sed -i "s,www-data,travis,g" examples/api/api.conf
  - sed -i "s,^# ,," examples/api/api.wsgi
  - sed -i "s,/path/to/,$VIRTUAL_ENV/," examples/api/api.wsgi
  - sudo cp examples/api/api.conf /etc/apache2/sites-available/
  - sudo a2enmod rewrite
  - sudo a2enmod ssl
  - sudo a2ensite api.conf
  - cp examples/api/api.wsgi $TRAVIS_BUILD_DIR
  - cp examples/vctoolsrc.yaml $TRAVIS_BUILD_DIR
script:
  - find . -not \( -name ".venv" -prune \) -name "*.py" -type f | xargs pylint --rcfile=.pylintrc
  - python main.py --version
  - sudo service apache2 restart
  - curl -Ik --tlsv1.2 https://hostname.domain.com/api | head -n 1 | grep OK

after_failure:
  - sudo cat /var/log/apache2/error.log
  - sudo cat /etc/apache2/sites-available/api.conf
  - sudo cat api.wsgi
  - ls -lh $TRAVIS_BUILD_DIR
  - sudo find / -name "activate_this.py" -type f
  - apachectl -M
